uint UINT_MAX = 0xFFFFFFFF;

layout(buffer_reference, scalar) readonly buffer Render_Globals {
	uint resolution_x;
    uint resolution_y;
    bool enable_panini;
};

layout(buffer_reference, scalar) readonly buffer Camera_Data {
	mat4 view;
	mat4 proj;
	mat4 view_proj;
    vec4 view_planes[6];
};

struct Transform {
    mat4 transform;
    uint parent_idx;
    uint8_t padding[12];
};
layout(buffer_reference, scalar) readonly buffer Transform_Buffer {
    Transform transforms[];
};
layout(buffer_reference, scalar) buffer Flattened_Transform_Buffer {
    mat4 transforms[];
};

struct Geo_Surface {
    uint idx_vertex;
    uint vertex_count;
    uint idx_index;
    uint index_count;

    uint default_material_instance; // Why keep this? why not just always use material overrides?
};
layout(buffer_reference, scalar) readonly buffer Geo_Surface_Buffer { 
    Geo_Surface geo_surfaces[];
};

struct Mesh_Instance {
    uint material_overrides[8]; // Num will be autogenerated when struct migration is ready
    uint idx_mesh_asset;
    uint idx_transform;
    uint idx_aabb;
    uint idx_geo_surface;
    uint8_t geo_surface_count;
    uint8_t generation;
};
layout(buffer_reference, scalar) readonly buffer Mesh_Instance_Buffer { 
    Mesh_Instance mesh_instances[];
};

struct Vertex {
	vec3 position;
	float uv_x;
	vec3 normal;
	float uv_y;
	vec4 color;
}; 
layout(buffer_reference, scalar) readonly buffer Vertex_Buffer { 
    Vertex vertices[];
};

struct Material_Instance {
    vec4 color_factors;
    uint albedo_image_index;
    uint albedo_sampler_index;
    uint8_t type;
    uint8_t padding[4];
};
layout(buffer_reference, scalar) readonly buffer Material_Buffer {
    Material_Instance materials[];
};

struct AABB {
    vec3 center;
    float pad0;
    vec3 half_extents;
    float pad1;
};
layout(buffer_reference, scalar) readonly buffer AABB_Buffer {
    AABB aabbs[];
};

struct VkDrawIndexedIndirectCommand {
    uint indexCount;
    uint instanceCount;
    uint firstIndex;
    uint vertexOffset;
    uint firstInstance;
};
struct Draw_Command {
    VkDrawIndexedIndirectCommand draw;
    uint idx_transform;
    uint idx_material_instance;
};
layout(buffer_reference, scalar) buffer Draw_Command_Buffer {
    uint count;
    Draw_Command commands[];
};

layout(buffer_reference, scalar) readonly buffer Draw_Address_Buffer {
    uint64_t bda_command_buffer_opaque;
    uint64_t bda_command_buffer_translucent;
    uint64_t bda_command_buffer_emissive;
    uint64_t bda_commands_debug_wireframe;
};